// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7odzXIZoNZCL45x_7bD4bq_4nIZZmHl8',
    appId: '1:849394892409:web:07f1e7b3e85dcac3e89ea8',
    messagingSenderId: '849394892409',
    projectId: 'p5projekt-71fa8',
    authDomain: 'p5projekt-71fa8.firebaseapp.com',
    storageBucket: 'p5projekt-71fa8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM54fI3ozSYrEkFbJCRPZDLJX8q7BsU8E',
    appId: '1:849394892409:android:05985b0058ac550ee89ea8',
    messagingSenderId: '849394892409',
    projectId: 'p5projekt-71fa8',
    storageBucket: 'p5projekt-71fa8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDopns39PcJI_6HP_HGsWDbQXUo09mpWds',
    appId: '1:849394892409:ios:878a9258c5f41cb7e89ea8',
    messagingSenderId: '849394892409',
    projectId: 'p5projekt-71fa8',
    storageBucket: 'p5projekt-71fa8.appspot.com',
    iosBundleId: 'com.example.p5',
  );
}
